# Generated by Django 4.0.3 on 2022-04-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_comments',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='date',
            field=models.DateField(),
        ),
    ]
