# Generated by Django 4.0.3 on 2022-04-12 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_comments_date_alter_blog_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 11)),
        ),
    ]
